config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/r-sarma/itwinai-tests:
      branch: main
      repo: https://github.com/r-sarma/itwinai-tests
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/r-sarma/itwinai-tests git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cardinal-numbat.sh
        container: qc.acc_cozy-sapphire-argentino
  QC.Doc:
    repos:
      github.com/r-sarma/itwinai-tests find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aquamarine-swan.sh
        container: qc.doc_seedy-ultramarine-kangaroo
      github.com/r-sarma/itwinai-tests git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-sangria-skunk.sh
        container: qc.doc_crappy-coral-akita
      github.com/r-sarma/itwinai-tests markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cinnabar-bison.sh
        container: qc.doc_fuzzy-cerulean-angelfish
      github.com/r-sarma/itwinai-tests restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-emerald-slug.sh
        container: qc.doc_crabby-maroon-opossum
  QC.Lic:
    repos:
      github.com/r-sarma/itwinai-tests licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chestnut-whale.sh
        container: qc.lic_nerdy-vermilion-fly
  QC.Met:
    repos:
      github.com/r-sarma/itwinai-tests cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-xanthic-jellyfish.sh
        container: qc.met_craggy-wheat-cheetah
  QC.Sec:
    repos:
      github.com/r-sarma/itwinai-tests bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-gamboge-terrier.sh
        container: qc.sec_stuffy-azure-bonobo
  QC.Sty:
    repos:
      github.com/r-sarma/itwinai-tests flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-periwinkle-bird.sh
        container: qc.sty_lousy-taupe-beetle
      github.com/r-sarma/itwinai-tests hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-heliotrope-beagle.sh
        container: qc.sty_slimy-cerulean-rhinoceros
      github.com/r-sarma/itwinai-tests jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-scarlet-devil.sh
        container: qc.sty_cloudy-malachite-llama
  QC.Uni:
    repos:
      github.com/r-sarma/itwinai-tests commands:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cobalt-sloth.sh
        container: qc.uni_hazy-copper-labradoodle
  QC.Ver:
    repos:
      github.com/r-sarma/itwinai-tests get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lavender-liger.sh
        container: qc.ver_muggy-puce-caterpillar
timeout: 5400
